// Code generated by protoc-gen-go.
// source: BatchUpdateBean.proto
// DO NOT EDIT!

/*
Package helloworld is a generated protocol buffer package.

It is generated from these files:
	BatchUpdateBean.proto

It has these top-level messages:
	EncryptRequest
	EncryptReply
*/
package helloworld

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EncryptRequest struct {
	Customers  []string `protobuf:"bytes,1,rep,name=customers" json:"customers,omitempty"`
	Platform   string   `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	TenantId   string   `protobuf:"bytes,3,opt,name=tenantId" json:"tenantId,omitempty"`
	PropertyId string   `protobuf:"bytes,4,opt,name=propertyId" json:"propertyId,omitempty"`
	Value      string   `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
}

func (m *EncryptRequest) Reset()                    { *m = EncryptRequest{} }
func (m *EncryptRequest) String() string            { return proto.CompactTextString(m) }
func (*EncryptRequest) ProtoMessage()               {}
func (*EncryptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EncryptRequest) GetCustomers() []string {
	if m != nil {
		return m.Customers
	}
	return nil
}

func (m *EncryptRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *EncryptRequest) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *EncryptRequest) GetPropertyId() string {
	if m != nil {
		return m.PropertyId
	}
	return ""
}

func (m *EncryptRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EncryptReply struct {
	Customers  []string `protobuf:"bytes,1,rep,name=customers" json:"customers,omitempty"`
	Platform   string   `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	TenantId   string   `protobuf:"bytes,3,opt,name=tenantId" json:"tenantId,omitempty"`
	PropertyId string   `protobuf:"bytes,4,opt,name=propertyId" json:"propertyId,omitempty"`
	Value      string   `protobuf:"bytes,5,opt,name=value" json:"value,omitempty"`
}

func (m *EncryptReply) Reset()                    { *m = EncryptReply{} }
func (m *EncryptReply) String() string            { return proto.CompactTextString(m) }
func (*EncryptReply) ProtoMessage()               {}
func (*EncryptReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EncryptReply) GetCustomers() []string {
	if m != nil {
		return m.Customers
	}
	return nil
}

func (m *EncryptReply) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *EncryptReply) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *EncryptReply) GetPropertyId() string {
	if m != nil {
		return m.PropertyId
	}
	return ""
}

func (m *EncryptReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*EncryptRequest)(nil), "helloworld.EncryptRequest")
	proto.RegisterType((*EncryptReply)(nil), "helloworld.EncryptReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Encrypt service

type EncryptClient interface {
	ToEncrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptReply, error)
}

type encryptClient struct {
	cc *grpc.ClientConn
}

func NewEncryptClient(cc *grpc.ClientConn) EncryptClient {
	return &encryptClient{cc}
}

func (c *encryptClient) ToEncrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptReply, error) {
	out := new(EncryptReply)
	err := grpc.Invoke(ctx, "/helloworld.Encrypt/ToEncrypt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Encrypt service

type EncryptServer interface {
	ToEncrypt(context.Context, *EncryptRequest) (*EncryptReply, error)
}

func RegisterEncryptServer(s *grpc.Server, srv EncryptServer) {
	s.RegisterService(&_Encrypt_serviceDesc, srv)
}

func _Encrypt_ToEncrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EncryptServer).ToEncrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Encrypt/ToEncrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EncryptServer).ToEncrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Encrypt_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Encrypt",
	HandlerType: (*EncryptServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToEncrypt",
			Handler:    _Encrypt_ToEncrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BatchUpdateBean.proto",
}

func init() { proto.RegisterFile("BatchUpdateBean.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x75, 0x4a, 0x2c, 0x49,
	0xce, 0x08, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x75, 0x4a, 0x4d, 0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0xca, 0x48, 0xcd, 0xc9, 0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0x51, 0x9a, 0xc3,
	0xc8, 0xc5, 0xe7, 0x9a, 0x97, 0x5c, 0x54, 0x59, 0x50, 0x12, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c,
	0x22, 0x24, 0xc3, 0xc5, 0x99, 0x5c, 0x5a, 0x5c, 0x92, 0x9f, 0x9b, 0x5a, 0x54, 0x2c, 0xc1, 0xa8,
	0xc0, 0xac, 0xc1, 0x19, 0x84, 0x10, 0x10, 0x92, 0xe2, 0xe2, 0x28, 0xc8, 0x49, 0x2c, 0x49, 0xcb,
	0x2f, 0xca, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x25, 0xa9, 0x79,
	0x89, 0x79, 0x25, 0x9e, 0x29, 0x12, 0xcc, 0x10, 0x39, 0x18, 0x5f, 0x48, 0x8e, 0x8b, 0xab, 0xa0,
	0x28, 0xbf, 0x20, 0xb5, 0xa8, 0xa4, 0xd2, 0x33, 0x45, 0x82, 0x05, 0x2c, 0x8b, 0x24, 0x22, 0x24,
	0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x2a, 0xc1, 0x0a, 0x96, 0x82, 0x70, 0x94, 0x66, 0x31,
	0x72, 0xf1, 0xc0, 0x9d, 0x57, 0x90, 0x53, 0x39, 0x98, 0x1c, 0x67, 0xe4, 0xc7, 0xc5, 0x0e, 0x75,
	0x9b, 0x90, 0x33, 0x17, 0x67, 0x48, 0x3e, 0x8c, 0x23, 0xa5, 0x87, 0x08, 0x60, 0x3d, 0xd4, 0xc0,
	0x95, 0x92, 0xc0, 0x2a, 0x57, 0x90, 0x53, 0xa9, 0xc4, 0x90, 0xc4, 0x06, 0x8e, 0x1e, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x20, 0x73, 0xd1, 0xb7, 0x01, 0x00, 0x00,
}
